name: Update Profile Metrics

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

concurrency:
  group: profile-update
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Contribution calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: profile/calendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Africa/Lagos
